---
- hosts: all
  become: yes
  tasks:
  - name: i want to start webserver on ubuntu 16 node
    service:
     name: apache2
     state: started
    when: ansible_os_family=="Debian" 
  
  - name: i want to install webserver on RedHat node
    service:
     name: httpd
     state: started
    when: ansible_os_family=="RedHat" 