--- 
- name: give tomcat the owernship
  file:
   path: /opt/tomcat
   state: directory
   group: tomcat
   recurse: yes

- name: give tomcat read access to the conf directory
  file: 
   path: /opt/tomcat/conf
   state: directory
   mode: g+r
   recurse: yes

- name: give tomcat read access to the conf directory
  file: 
   path: /opt/tomcat/conf
   state: directory
   mode: g+x
   

- name: make tomcat user  the owner of webapps
  file: 
   path: /opt/tomcat/webapps
   state: directory
   owner: tomcat
   recurse: yes

- name: make tomcat user  the owner of work
  file: 
   path: /opt/tomcat/work
   state: directory
   owner: tomcat
   recurse: yes

- name: make tomcat user  the owner of temp
  file: 
   path: /opt/tomcat/temp
   state: directory
   owner: tomcat
   recurse: yes


- name: make tomcat user  the owner of logs
  file: 
   path: /opt/tomcat/logs
   state: directory
   owner: tomcat
   recurse: yes      